const actionTypes = {
  // auth
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
  LOGOUT: "LOGOUT",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAIL: "REGISTER_FAIL",
  GET_CURRENT: "GET_CURRENT",
  //Home-nav
  SHOW_HOMENAV: "SHOW_HOMENAV",
  HIDDEN_HOMENAV: "HIDDEN_HOMENAV",
  // user
  SAVE_USERID_TOKEN: "SAVE_USERID_TOKEN",
  SAVE_TOKEN_VERIFY_EMAIL: "SAVE_TOKEN_VERIFY_EMAIL",
  //app
  TOGGLE_POPUP: "TOGGLE_POPUP",

  //search
  SET_SEARCH_KEYWORD: "SET_SEARCH_KEYWORD",
  // product
  GET_PRODUCT: "GET_PRODUCT",
  GET_PRODUCT_BEST_SELLER: "GET_PRODUCT_BEST_SELLER",
  GET_PRODUCT_CURRENT_UPDATE: "GET_PRODUCT_CURRENT_UPDATE",
  GET_PRODUCT_BY_ID: "GET_PRODUCT_BY_ID",
  ADD_TO_CART: "ADD_TO_CART",
  DETELE_ALL: "DELETE_ALL",
  ADD_TO_PAYMENT: "ADD_TO_PAYMENT",
  DELETE_FROM_PAYMENT: "DELETE_FROM_PAYMENT",
  UPDATE_PAYMENT: "UPDATE_PAYMENT",
  DELETE_ALL_PAYMENTS: "DELETE_ALL_PAYMENTS",

  GET_PRODUCTS: "GET_PRODUCTS",
  GET_LASTEST_PRODUCTS: "GET_LASTEST_PRODUCTS",
  GET_TOP_PRODUCTS: "GET_TOP_PRODUCTS",
  GET_FAVORITE_PRODUCTS: "GET_FAVORITE_PRODUCTS",
  // category
  GET_CATEGORY: "GET_CATEGORY",
  GET_CODE_CATEGORIES: "GET_CODE_CATEGORIES",

  // app
  DETAIL_ORDER: "DETAIL_ORDER",
  // cart
  FETCH_CART_QUANTITY: "FETCH_CART_QUANTITY",
  DELETE_ALL_CART: "DETETE_ALL_CART",
  PLACE_ORDER_CART: "PLACE_ORDER_CART",


  // chatbot
  MESSAGE_USER: 'MESSAGE_USER',
  MESSAGE_BOT: 'MESSAGE_BOT',
  BUY: 'BUY',
  CANCEL_BUY: 'CANCEL_BUY',
  UPDATE_QUANTITY: 'UPDATE_QUANTITY',
  BOT_LOADING: 'BOT_LOADING',

  //wishlist
  GET_ALL_WISHLIST: 'GET_ALL_WISHLIST',
};

export default actionTypes;
