export { default as System } from "./System";
export { default as Sidebar } from "./Sidebar";
export { default as General } from "./General";
export { default as EditProduct } from "./CreateProduct";
export { default as ManageProduct } from "./ManageProduct";
export { default as ManageCategory } from "./ManageCategory";
export { default as User } from "./User";
export { default as Bill } from "./Bill";
export { default as UpdateProfile } from "./UpdateProfile";
export { default as Profile } from './Profile'
export { default as PersonalInformation } from './PersonalInformation'
export { default as Orders } from './Orders'
export { default as Analyst } from './Analyst'