export { default as InputField } from './InputField'
export { default as Button } from './Button'
export { default as Loading } from './Loading'
export { default as HeaderLaptop } from './HeaderLaptop'
export { default as Search } from './Search'
export { default as Slider } from './Slider'
export { default as HomeItem } from './HomeItem'
export { default as ProductItem } from './ProductItem'
export { default as Footer } from './Footer'
export { default as Button2 } from './Button2'
export { default as SidebarProfile } from './SidebarProfile'
export { default as OrderItem } from './OrderItem'
export { default as DetailOrder } from './DetailOrder'
export { default as Contact } from './Contact'
export { default as LongButton } from './LongButton'
export { default as BoxChat } from './BoxChat'
export { default as BotLoading } from './BotLoading'
export { default as DetailProductChatbot } from './DetailProductChatbot'


